from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('managePlace', views.managePlace, name='managePlace'),
    path('showLicense', views.showLicense, name='showLicense'),
    path('loginLog', views.login_log, name='loginLog'),
    path('user', views.user, name='user'),
    path('staff', views.staff, name='staff'),
    path('manageUser', views.manageUser, name='manageUser'),
    path('editUser/<int:id>', views.edit_user, name='editUser'),
    path('changePassword/<int:id>', views.change_password, name='changePassword'),
    path('deleteUser/<int:id>', views.delete_user, name='deleteUser'),
    path('manageUser/<int:id>', views.user_info, name='userInfo'),
    path('manageStore', views.manageStore, name='manageStore'),
    path('editStore/<int:id>', views.edit_store, name='editStore'),
    path('deleteStore/<int:id>', views.delete_store, name='deleteStore'),
    path('manageStore/<int:id>', views.store_info, name='storeInfo'),
    path('staffStore/<int:id>', views.staff_store_info, name='staffstoreInfo'),
    path('mapinfo/<int:id>', views.map_info, name='mapinfo'),
    path('imgupload/<int:id>',views.img_upload, name="imgupload"),
    path('deleteImg/<int:storeid>/<int:id>',views.delete_img, name="deleteImg"),
    path('addData', views.addData, name='addData'),
    path('addData/excel', views.addExcel, name='addExcel'),
    path('addData/form', views.addDataForm, name='addDataForm'),
    path('addData2', views.addData2, name='addData2'),
    path('addUtility', views.addUtility, name='addUtility'),
    path('addUtilityPost', views.addUtilityPost, name='addUtilityPost'),
    path('saveStoreOwner/<int:id>',views.save_store_owner, name="saveStoreOwner"),
    path('userUtility',views.user_utility, name="userUtility"),
    path('exportUser.xlsx',views.export_user, name="exportUser"),
    path('exportStore.xlsx',views.export_store,  name="exportStore"),
]