# Generated by Django 3.2.6 on 2021-09-22 13:56

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latlong', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modify_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water', models.FloatField(default=0.0)),
                ('electric', models.FloatField(default=0.0)),
                ('wash', models.FloatField(default=0.0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.store')),
            ],
        ),
        migrations.CreateModel(
            name='Map_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.store'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
